const apiUrl = 'https://api.jikan.moe/v4';
const genres = [
  {"mal_id": 1, "name": "Action", urlName: 'action'},
  {"mal_id": 2, "name": "Adventure", urlName: 'adventure'},
  {"mal_id": 5, "name": "Avant Garde", urlName: 'avant-garde'},
  {"mal_id": 46, "name": "Award Winning", urlName: 'award-winning'},
  {"mal_id": 28, "name": "Boys Love", urlName: 'boys-love'},
  {"mal_id": 4, "name": "Comedy", urlName: 'comedy'},
  {"mal_id": 8, "name": "Drama", urlName: 'drama'},
  {"mal_id": 10, "name": "Fantasy", urlName: 'fantasy'},
  {"mal_id": 26, "name": "Girls Love", urlName: 'girls-love'},
  {"mal_id": 47, "name": "Gourmet", urlName: 'gourmet'},
  {"mal_id": 14, "name": "Horror", urlName: 'horror'},
  {"mal_id": 7, "name": "Mystery", urlName: 'mystery'},
  {"mal_id": 22, "name": "Romance", urlName: 'romance'},
  {"mal_id": 24, "name": "Sci-Fi", urlName: 'sci-fi'},
  {"mal_id": 36, "name": "Slice of Life", urlName: 'slice-of-life'},
  {"mal_id": 30, "name": "Sports", urlName: 'sports'},
  {"mal_id": 37, "name": "Supernatural", urlName: 'supernatural'},
  {"mal_id": 41, "name": "Suspense", urlName: 'suspense'},
  {"mal_id": 9, "name": "Ecchi", urlName: 'ecchi'},
  {"mal_id": 49, "name": "Erotica", urlName: 'erotica'},
  {"mal_id": 51, "name": "Anthropomorphic", urlName: 'anthropomorphic'},
  {"mal_id": 52, "name": "CGDCT", urlName: 'cgdct'},
  {"mal_id": 53, "name": "Childcare", urlName: 'childcare'},
  {"mal_id": 54, "name": "Combat Sports", urlName: 'combat-sports'},
  {"mal_id": 81, "name": "Crossdressing", urlName: 'crossdressing'},
  {"mal_id": 55, "name": "Delinquents", urlName: 'delinquents'},
  {"mal_id": 39, "name": "Detective", urlName: 'detective'},
  {"mal_id": 56, "name": "Educational", urlName: 'educational'},
  {"mal_id": 57, "name": "Gag Humor", urlName: 'gag-humor'},
  {"mal_id": 58, "name": "Gore", urlName: 'gore'},
  {"mal_id": 35, "name": "Harem", urlName: 'harem'},
  {"mal_id": 59, "name": "High Stakes Game", urlName: 'high-stakes-game'},
  {"mal_id": 13, "name": "Historical", urlName: 'historical'},
  {"mal_id": 60, "name": "Idols (Female)", urlName: 'idols-female'},
  {"mal_id": 61, "name": "Idols (Male)", urlName: 'idols-male'},
  {"mal_id": 62, "name": "Isekai", urlName: 'isekai'},
  {"mal_id": 63, "name": "Iyashikei", urlName: 'iyashikei'},
  {"mal_id": 64, "name": "Love Polygon", urlName: 'love-polygon'},
  {"mal_id": 65, "name": "Magical Sex Shift", urlName: 'magical-sex-shift'},
  {"mal_id": 66, "name": "Mahou Shoujo", urlName: 'mahou-shoujo'},
  {"mal_id": 17, "name": "Martial Arts", urlName: 'martial-arts'},
  {"mal_id": 18, "name": "Mecha", urlName: 'mecha'},
  {"mal_id": 67, "name": "Medical", urlName: 'medical'},
  {"mal_id": 38, "name": "Military", urlName: 'military'},
  {"mal_id": 19, "name": "Music", urlName: 'music'},
  {"mal_id": 6, "name": "Mythology", urlName: 'mythology'},
  {"mal_id": 68, "name": "Organized Crime", urlName: 'organized-crime'},
  {"mal_id": 69, "name": "Otaku Culture", urlName: 'otaku-culture'},
  {"mal_id": 20, "name": "Parody", urlName: 'parody'},
  {"mal_id": 70, "name": "Performing Arts", urlName: 'performing-arts'},
  {"mal_id": 71, "name": "Pets", urlName: 'pets'},
  {"mal_id": 40, "name": "Psychological", urlName: 'psychological'},
  {"mal_id": 3, "name": "Racing", urlName: 'racing'},
  {"mal_id": 72, "name": "Reincarnation", urlName: 'reincarnation'},
  {"mal_id": 73, "name": "Reverse Harem", urlName: 'reverse-harem'},
  {"mal_id": 74, "name": "Romantic Subtext", urlName: 'romantic-subtext'},
  {"mal_id": 21, "name": "Samurai", urlName: 'samurai'},
  {"mal_id": 23, "name": "School", urlName: 'school'},
  {"mal_id": 75, "name": "Showbiz", urlName: 'showbiz'},
  {"mal_id": 29, "name": "Space", urlName: 'space'},
  {"mal_id": 11, "name": "Strategy Game", urlName: 'strategy-game'},
  {"mal_id": 31, "name": "Super Power", urlName: 'super-power'},
  {"mal_id": 76, "name": "Survival", urlName: 'survival'},
  {"mal_id": 77, "name": "Team Sports", urlName: 'team-sports'},
  {"mal_id": 78, "name": "Time Travel", urlName: 'time-travel'},
  {"mal_id": 32, "name": "Vampire", urlName: 'vampire'},
  {"mal_id": 79, "name": "Video Game", urlName: 'video-game'},
  {"mal_id": 80, "name": "Visual Arts", urlName: 'visual-arts'},
  {"mal_id": 48, "name": "Workplace", urlName: 'workplace'},
  {"mal_id": 43, "name": "Josei", urlName: 'josei'},
  {"mal_id": 15, "name": "Kids", urlName: 'kids'},
  {"mal_id": 42, "name": "Seinen", urlName: 'seinen'},
  {"mal_id": 25, "name": "Shoujo", urlName: 'shoujo'},
  {"mal_id": 27, "name": "Shounen", urlName: 'shounen'}
];


const types = [
  {id: 'tv', name:'Animes', urlName: 'animes'},
  {id:'movie', name: 'Movies', urlName: 'movies'},
  {id: 'special', name: 'Specials', urlName: 'special'},
  {id:'ova', name: 'Ovas', urlName: 'ova'},
  {id:'ona', name: 'Onas', urlName: 'onas'}
];



export { apiUrl, genres, types };